name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2.0.1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Generate Prisma client
        run: bun run prisma generate
      - name: Run migrations
        run: bun run prisma migrate deploy
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
